# Generated by Django 3.1 on 2022-04-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['created']},
        ),
    ]
